version: "3.8"

services:
  course:
    build:
      context: .
      dockerfile: /course/Dockerfile
    ports:
      - "8080:8080"
    container_name: course-core
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/course
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=none
    depends_on:
      - database
  database:
    image: 'postgres:13.1-alpine'
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data