version: "3.8"

services:
  course:
    build:
      context: .
      dockerfile: course/Dockerfile
    restart: on-failure
    container_name: course-core
    ports:
      - 8090:8080
      - 5005:5005
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
    - POSTGRES_USER=compose-postgres
    - POSTGRES_PASSWORD=compose-postgres